/*=========================================================
 LAB 4 : UPDATE QUERIES
=========================================================*/

-- 1
UPDATE STUDENT
SET SPI = 8.00
WHERE SPI = 7.00;

-- 2
UPDATE STUDENT
SET CITY = 'AHMEDABAD'
WHERE SNAME = 'HETVI'
AND CITY = 'RAJKOT';

-- 3
UPDATE STUDENT
SET SPI = 9.20,
    CITY = 'VADODARA'
WHERE SNAME = 'DEEP';

-- 4
UPDATE STUDENT
SET SPI = 8.50
WHERE SNAME = 'DHARMIK';

-- 5
UPDATE STUDENT
SET BRANCH = 'IT'
WHERE BRANCH = 'COMPUTER';

-- 6
UPDATE STUDENT
SET BRANCH = 'AUTOMOBILE'
WHERE SNAME = 'RAJ';

-- 7
UPDATE STUDENT
SET SPI = 7.50
WHERE STDID BETWEEN 103 AND 107;

-- 8
UPDATE STUDENT
SET CITY = 'MUMBAI'
WHERE SNAME = 'PARAG';

-- 9
UPDATE STUDENT
SET SPI = 6.00
WHERE SNAME = 'RIYA';

-- 10
UPDATE STUDENT
SET SPI = 7.20,
    BRANCH = 'ELECTRICAL'
WHERE SNAME = 'SMAIR';

-- 11
UPDATE STUDENT
SET SPI = SPI + (SPI * 10 / 100);

-- 12
UPDATE STUDENT
SET SPI = SPI + (SPI * 20 / 100);

-- 13
UPDATE STUDENT
SET SPI = SPI + 0.50;

-- 14
UPDATE STUDENT
SET BRANCH = 'EC',
    SPI = 8.00,
    CITY = 'SURAT'
WHERE SNAME = 'KRUNAL';

-- 15
UPDATE STUDENT
SET CITY = 'RAJKOT',
    SPI = 7.00
WHERE BRANCH = 'CIVIL'
AND STDID < 105;

-- 16
UPDATE STUDENT
SET SPI = NULL
WHERE STDID = 110;

-- 17
UPDATE STUDENT
SET BRANCH = NULL
WHERE SNAME = 'VISHA';

-- 18
SELECT *
FROM STUDENT
WHERE SPI IS NULL;

-- 19
SELECT *
FROM STUDENT
WHERE BRANCH IS NOT NULL;

-- 20
UPDATE STUDENT
SET SNAME = 'DARSHAN',
    BRANCH = 'COMPUTER',
    SPI = 8.50
WHERE STDID = 108;

-- 21
UPDATE STUDENT
SET CITY = 'SURAT'
WHERE SPI < 7.00;

-- 22
UPDATE STUDENT
SET CITY = NULL,
    BRANCH = 'MECHANICAL'
WHERE STDID = 109;


/*=========================================================
 LAB 5 : ALTER, RENAME, DELETE, TRUNCATE & DROP
=========================================================*/

-- 1
ALTER TABLE DEPOSIT
ADD STATE VARCHAR(20);

-- 2
ALTER TABLE DEPOSIT
ADD CITY VARCHAR(20),
ADD PINCODE INT;

-- 3
ALTER TABLE DEPOSIT
MODIFY CNAME VARCHAR(35);

-- 4
ALTER TABLE DEPOSIT
MODIFY AMOUNT INT;

-- 5
ALTER TABLE DEPOSIT
DROP COLUMN CITY;

-- 6
ALTER TABLE DEPOSIT
RENAME COLUMN ACTNO TO ANO;

-- 7
ALTER TABLE DEPOSIT
RENAME COLUMN BNAME TO BRANCH_NAME;

-- 8
ALTER TABLE DEPOSIT
RENAME TO DEPOSIT_DETAIL;

-- 9
ALTER TABLE DEPOSIT_DETAIL
ADD IFSC_CODE VARCHAR(15);

-- 10
ALTER TABLE DEPOSIT_DETAIL
MODIFY BRANCH_NAME VARCHAR(30);

-- 11
ALTER TABLE DEPOSIT_DETAIL
RENAME COLUMN ADATE TO AOPENDATE;

-- 12
ALTER TABLE DEPOSIT_DETAIL
DROP COLUMN AOPENDATE;

-- 13
ALTER TABLE DEPOSIT_DETAIL
RENAME COLUMN CNAME TO CUSTOMER_NAME;

-- 14
ALTER TABLE DEPOSIT_DETAIL
ADD COUNTRY VARCHAR(20);

-- 15
ALTER TABLE DEPOSIT_DETAIL
ADD ACCOUNT_TYPE VARCHAR(15);